#!/usr/bin/env python3
"""
Apply the iptables DNS-redirect plan to the router, ONE rule at a time.

Plan: redirect DNS traffic from the Capsula (192.168.0.11) to the
operator's PC (192.168.0.22:53), so we can log what domains the speaker
asks for.

Strict operator rules (paraphrased):
  1   no reboot
  2   no factory reset
  3   no firmware update
  4   no file deletion / rm -rf
  6   no killing existing services (vpn / xray / httpd / dropbear / dnsmasq)
  7   no changes to WAN / PPPoE / LAN / Wi-Fi / DHCP / firewall defaults
  11  only allowed change = the iptables rules described here
  13  print every command + reason BEFORE running it
  14  end with: iptables -t nat -S PREROUTING; iptables -t nat -S OUTPUT; ps; mount
  15  if anything is unexpected, stop

This script implements rules 13 and 14 verbatim and aborts on the first
non-zero rc from any iptables modification.
"""
import sys
import time

import paramiko

ROUTER_HOST = "192.168.0.1"
ROUTER_USER = "superadmin"
ROUTER_PASS = "8WHoDt3yCQR98BRx"
LAN_IFACE = "br2"
CAPSULA_IP = "192.168.0.11"
PC_IP = "192.168.0.22"

# Each rule = (label, ADD command, ROLLBACK command, reason)
RULES = [
    (
        "DNAT_UDP_53",
        f"iptables -t nat -I PREROUTING 1 -i {LAN_IFACE} -s {CAPSULA_IP} -p udp --dport 53 -j DNAT --to-destination {PC_IP}:53",
        f"iptables -t nat -D PREROUTING   -i {LAN_IFACE} -s {CAPSULA_IP} -p udp --dport 53 -j DNAT --to-destination {PC_IP}:53",
        "redirect Capsula UDP DNS queries to PC",
    ),
    (
        "DNAT_TCP_53",
        f"iptables -t nat -I PREROUTING 1 -i {LAN_IFACE} -s {CAPSULA_IP} -p tcp --dport 53 -j DNAT --to-destination {PC_IP}:53",
        f"iptables -t nat -D PREROUTING   -i {LAN_IFACE} -s {CAPSULA_IP} -p tcp --dport 53 -j DNAT --to-destination {PC_IP}:53",
        "redirect Capsula TCP DNS queries to PC (large responses fall back to TCP)",
    ),
    (
        "MASQ_UDP_53",
        f"iptables -t nat -I POSTROUTING 1 -s {CAPSULA_IP} -d {PC_IP} -p udp --dport 53 -j MASQUERADE",
        f"iptables -t nat -D POSTROUTING   -s {CAPSULA_IP} -d {PC_IP} -p udp --dport 53 -j MASQUERADE",
        "rewrite source so PC reply returns via the router (otherwise Capsula drops it as spoof)",
    ),
    (
        "MASQ_TCP_53",
        f"iptables -t nat -I POSTROUTING 1 -s {CAPSULA_IP} -d {PC_IP} -p tcp --dport 53 -j MASQUERADE",
        f"iptables -t nat -D POSTROUTING   -s {CAPSULA_IP} -d {PC_IP} -p tcp --dport 53 -j MASQUERADE",
        "same SNAT logic for the TCP/53 fallback",
    ),
]


def ssh_connect():
    print(f"[*] connecting to {ROUTER_USER}@{ROUTER_HOST} ...")
    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect(
        hostname=ROUTER_HOST,
        username=ROUTER_USER,
        password=ROUTER_PASS,
        timeout=15,
        allow_agent=False,
        look_for_keys=False,
    )
    print("[*] connected.")
    return c


def run(client, cmd, label="", show=True, timeout=20):
    if show:
        print(f"  $ {cmd}")
    stdin, stdout, stderr = client.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    rc = stdout.channel.recv_exit_status()
    if show and out:
        for line in out.splitlines()[:60]:
            print(f"    {line}")
        if len(out.splitlines()) > 60:
            print(f"    ... [+{len(out.splitlines()) - 60} more lines]")
    if err.strip():
        for line in err.splitlines()[:20]:
            print(f"    [stderr] {line}")
    if show and rc != 0:
        print(f"    (rc={rc})")
    return rc, out, err


def write_rollback_file(path):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("#!/bin/sh\n")
        f.write("# Rollback DNS-redirect for Capsula. Apply on the router.\n")
        f.write("# Generated by router_apply_dns_redirect.py\n\n")
        for label, _add, undo, _why in RULES:
            f.write(f"# {label}\n")
            f.write(undo + "\n\n")
    print(f"[*] rollback commands also written to {path}")


def main():
    print("=" * 70)
    print("Applying DNS redirect rules on router")
    print(f"  router: {ROUTER_HOST}   LAN iface: {LAN_IFACE}")
    print(f"  source: {CAPSULA_IP}    target:    {PC_IP}:53")
    print("=" * 70)

    print("\n[*] Rules to apply (rule 13: announced before any change):")
    for label, add, undo, why in RULES:
        print(f"\n  -- {label} --  reason: {why}")
        print(f"     ADD:      {add}")
        print(f"     ROLLBACK: {undo}")

    print("\n[*] Full rollback (paste on router shell to revert ALL changes):\n")
    for _l, _a, undo, _w in RULES:
        print(f"   {undo}")
    print()

    write_rollback_file(r"c:\Users\DUROV\Documents\New project 6\router_rollback_dns_redirect.sh")

    client = ssh_connect()

    # Sanity: confirm we're root and br2 exists with our IP
    print("\n[*] Pre-flight sanity:")
    run(client, "id")
    run(client, f"ip -o addr show dev {LAN_IFACE} 2>/dev/null || ifconfig {LAN_IFACE}")
    arp_pat = CAPSULA_IP.replace(".", "\\.")
    arp_cmd = "grep -E '\\b" + arp_pat + "\\b' /proc/net/arp || echo 'capsula not in ARP yet'"
    run(client, arp_cmd)

    # Apply rules one-by-one
    applied = []
    for label, add, undo, why in RULES:
        print("\n" + "-" * 70)
        print(f"[{label}] reason: {why}")
        rc, _, _ = run(client, add)
        if rc != 0:
            print(f"\n[!] {label} FAILED (rc={rc}). Rolling back what was applied.")
            for prev_label, _a, prev_undo, _w in reversed(applied):
                print(f"  rolling back {prev_label}")
                run(client, prev_undo)
            client.close()
            sys.exit(2)
        # verify the rule shows up
        verify = (
            "iptables -t nat -L PREROUTING -n -v | head -5"
            if label.startswith("DNAT") else
            "iptables -t nat -L POSTROUTING -n -v | head -5"
        )
        print(f"  verify:")
        run(client, verify)
        applied.append((label, add, undo, why))
        time.sleep(0.2)

    # Final state per rule 14
    print("\n" + "=" * 70)
    print("Final state (rule 14)")
    print("=" * 70)
    for cmd in [
        "iptables -t nat -S PREROUTING",
        "iptables -t nat -S OUTPUT",
        "ps w 2>/dev/null | head -100 || ps -ef | head -100",
        "mount",
    ]:
        print(f"\n  $ {cmd}")
        run(client, cmd, show=True)

    client.close()

    print("\n" + "=" * 70)
    print("Done. DNS redirect is LIVE.")
    print("=" * 70)
    print(f"""
What to do next:
  1) Start DNS logger on PC (Administrator PowerShell):
     python "c:\\Users\\DUROV\\Documents\\New project 6\\capsula_mitm\\dns_logger.py" --filter-client {CAPSULA_IP}
  2) Allow Python through Windows Firewall on Private profile if asked.
  3) Power-cycle the Capsula (unplug -> 10s -> plug back in) to provoke a
     fresh DNS storm: NTP, OTA-check, telemetry, voice gateway.
  4) Talk to it ("Маруся, который час?"). Open the Маруся app, run
     "Check for updates" on the speaker.
  5) After ~10-30 minutes, run:
     python "c:\\Users\\DUROV\\Documents\\New project 6\\capsula_mitm\\parse_dns_log.py" --client {CAPSULA_IP}

Rollback:
  Re-run on the router any time:
     sh < router_rollback_dns_redirect.sh
  or paste the four `iptables -t nat -D ...` lines printed above.
""")


if __name__ == "__main__":
    main()
