#!/bin/sh
# Rollback DNS-redirect for Capsula. Apply on the router.
# Generated by router_apply_dns_redirect.py

# DNAT_UDP_53
iptables -t nat -D PREROUTING   -i br2 -s 192.168.0.11 -p udp --dport 53 -j DNAT --to-destination 192.168.0.22:53

# DNAT_TCP_53
iptables -t nat -D PREROUTING   -i br2 -s 192.168.0.11 -p tcp --dport 53 -j DNAT --to-destination 192.168.0.22:53

# MASQ_UDP_53
iptables -t nat -D POSTROUTING   -s 192.168.0.11 -d 192.168.0.22 -p udp --dport 53 -j MASQUERADE

# MASQ_TCP_53
iptables -t nat -D POSTROUTING   -s 192.168.0.11 -d 192.168.0.22 -p tcp --dport 53 -j MASQUERADE

