#!/bin/bash
# sub.cgi -- public subscription endpoint for VPN clients (Hiddify, v2rayNG, etc).
#
#   GET /cgi-bin/sub.cgi?token=<sub_token>[&fmt=base64|text|singbox|clash]
#
# Returns the concatenated list of all transports for the wisd box.
# Format selection:
#   - base64 (default) -- "v2ray" universal subscription: newline-separated
#                         URLs, base64-encoded as a whole. Hiddify/v2rayNG
#                         understand this directly.
#   - text             -- raw newline-separated URLs (debug / manual copy).
#   - singbox          -- sing-box outbounds JSON.
#   - clash            -- Clash Meta YAML.
#
# Token lives at /var/lib/wisd/sub.token (regenerated by sub-rotate.cgi).

set -u
HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/lib.sh"
require_jq

parse_query

TOKEN_FILE=$WISD_STATE_DIR/sub.token
if [[ ! -s "$TOKEN_FILE" ]]; then
    printf 'Status: 503 Service Unavailable\r\n'
    printf 'Content-Type: text/plain; charset=utf-8\r\n\r\n'
    printf 'subscription not initialized\n'
    exit 0
fi
expected=$(tr -d '\r\n' < "$TOKEN_FILE")
given=${QPARAM[token]:-}

if [[ -z "$expected" || -z "$given" ]] || [[ "$expected" != "$given" ]]; then
    sleep 0.4 2>/dev/null || true
    printf 'Status: 404 Not Found\r\n'
    printf 'Content-Type: text/plain; charset=utf-8\r\n\r\n'
    printf 'not found\n'
    exit 0
fi

FMT=${QPARAM[fmt]:-base64}

SERVER_FILE=$WISD_STATE_DIR/server.json
if [[ ! -s "$SERVER_FILE" ]]; then
    printf 'Status: 500 Internal Server Error\r\n\r\nserver.json missing\n'
    exit 0
fi

# Build all transport URLs. Mirrors server.cgi but assembles into a single bundle.
python3 - "$SERVER_FILE" "$FMT" <<'PY'
import json, sys, base64, urllib.parse

server = json.load(open(sys.argv[1]))
fmt = sys.argv[2]
host = server.get('host', '')
uuid = server.get('uuid', '')

def vless_reality():
    q = {
        'encryption':'none','security':'reality',
        'sni': server.get('serverName',''),
        'fp': 'chrome',
        'pbk': server.get('publicKey',''),
        'sid': server.get('shortId',''),
        'type': 'tcp',
        'flow': server.get('flow',''),
    }
    return f"vless://{uuid}@{host}:{server.get('port',2053)}?{urllib.parse.urlencode(q)}#wisd-vless-reality"

def hy2():
    pw = server.get('hy2Pass','')
    q = {
        'insecure':'1',
        'sni': server.get('hy2Sni','www.bing.com'),
        'mport': f"{server.get('hy2PortLow',30000)}-{server.get('hy2PortHigh',50000)}",
    }
    return f"hysteria2://{pw}@{host}:{server.get('hy2Port',443)}?{urllib.parse.urlencode(q)}#wisd-hy2"

def tuic():
    tu = server.get('tuicUuid',''); tp = server.get('tuicPass','')
    q = {
        'congestion_control':'bbr','alpn':'h3',
        'sni': server.get('hy2Sni','www.bing.com'),
        'allow_insecure':'1','udp_relay_mode':'native',
    }
    return f"tuic://{tu}:{tp}@{host}:{server.get('tuicPort',8443)}?{urllib.parse.urlencode(q)}#wisd-tuic"

def cf_ws():
    cf_host = server.get('cfWorkerHost','')
    if not cf_host:
        return None
    path = server.get('wsPath','/')
    q = {
        'encryption':'none','security':'tls',
        'type':'ws','path':path,
        'host':cf_host,'sni':cf_host,'fp':'chrome',
    }
    return f"vless://{uuid}@{cf_host}:443?{urllib.parse.urlencode(q)}#wisd-cf-ws"

def ws_direct():
    ws_port = server.get('wsPort',10443)
    path = server.get('wsPath','/')
    q = {
        'encryption':'none','security':'none',
        'type':'ws','path':path,'host':host,
    }
    return f"vless://{uuid}@{host}:{ws_port}?{urllib.parse.urlencode(q)}#wisd-ws-direct"

urls = []
for fn in (vless_reality, hy2, tuic, cf_ws, ws_direct):
    u = fn()
    if u:
        urls.append(u)

body_text = '\n'.join(urls) + '\n'

if fmt == 'text':
    sys.stdout.write('Status: 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nCache-Control: no-store\r\n\r\n')
    sys.stdout.write(body_text)
elif fmt == 'singbox':
    # Outbounds for sing-box.
    out = []
    for u in urls:
        out.append({'type':'_url','url':u})
    cfg = {'outbounds': out}
    payload = json.dumps(cfg, indent=2, ensure_ascii=False)
    sys.stdout.write('Status: 200 OK\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-store\r\n\r\n')
    sys.stdout.write(payload + '\n')
elif fmt == 'clash':
    # Minimal Clash Meta proxy list (best-effort, only VLESS+Hy2+TUIC are mapped).
    lines = ["proxies:"]
    lines.append(f"  - {{name: 'wisd-vless', type: vless, server: '{host}', port: {server.get('port',2053)}, uuid: '{uuid}', network: tcp, flow: '{server.get('flow','')}', tls: true, reality-opts: {{public-key: '{server.get('publicKey','')}', short-id: '{server.get('shortId','')}'}}, client-fingerprint: chrome, servername: '{server.get('serverName','')}'}}")
    lines.append(f"  - {{name: 'wisd-hy2', type: hysteria2, server: '{host}', port: {server.get('hy2Port',443)}, password: '{server.get('hy2Pass','')}', sni: '{server.get('hy2Sni','')}', skip-cert-verify: true, ports: '{server.get('hy2PortLow',30000)}-{server.get('hy2PortHigh',50000)}'}}")
    lines.append(f"  - {{name: 'wisd-tuic', type: tuic, server: '{host}', port: {server.get('tuicPort',8443)}, uuid: '{server.get('tuicUuid','')}', password: '{server.get('tuicPass','')}', sni: '{server.get('hy2Sni','')}', alpn: [h3], congestion-controller: bbr, skip-cert-verify: true}}")
    sys.stdout.write('Status: 200 OK\r\nContent-Type: text/yaml; charset=utf-8\r\nCache-Control: no-store\r\n\r\n')
    sys.stdout.write('\n'.join(lines) + '\n')
else:
    # Default: base64-encoded list (universal v2ray/Hiddify format).
    encoded = base64.b64encode(body_text.encode('utf-8')).decode('ascii')
    sys.stdout.write('Status: 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nCache-Control: no-store\r\nProfile-Update-Interval: 12\r\nProfile-Title: wisd VPN bundle\r\n\r\n')
    sys.stdout.write(encoded + '\n')
PY
