#!/bin/sh
case "$1" in
  start|"")
    /var/LxC/vpnui-watchdog.sh start
    ;;
  stop)
    /var/LxC/vpnui-watchdog.sh stop
    ;;
  restart)
    /var/LxC/vpnui-watchdog.sh stop
    sleep 1
    /var/LxC/vpnui-watchdog.sh start
    ;;
esac
exit 0
